<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TencentCloudSDK" Version="3.0.1377" />
	</ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\extensions\KM\KernelMemory\KernelMemory.csproj" />
    </ItemGroup>

</Project>
